-- ============================================================
-- HENRINEWS - BANCO DE DADOS SUPABASE / POSTGRESQL
-- Execute este arquivo inteiro no SQL Editor do Supabase.
-- ============================================================

begin;

create extension if not exists pgcrypto with schema extensions;

-- ============================================================
-- 1. TABELAS
-- ============================================================

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null default 'Aluno',
    email text,
    role text not null default 'student' check (role in ('student', 'admin')),
    created_at timestamptz not null default now()
);

create table if not exists public.articles (
    id bigint generated by default as identity primary key,
    title text not null,
    content text not null,
    image_url text,
    status text not null default 'published' check (status in ('draft', 'published')),
    author_id uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.article_saves (
    user_id uuid not null references public.profiles(id) on delete cascade,
    article_id bigint not null references public.articles(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, article_id)
);

create table if not exists public.books (
    id bigint generated by default as identity primary key,
    title text not null,
    author text not null,
    description text,
    total_copies integer not null default 1 check (total_copies >= 0),
    available_copies integer not null default 1 check (available_copies >= 0),
    active boolean not null default true,
    created_at timestamptz not null default now(),
    constraint books_available_not_above_total check (available_copies <= total_copies)
);

create table if not exists public.loans (
    id bigint generated by default as identity primary key,
    code text not null unique,
    user_id uuid not null references public.profiles(id) on delete restrict,
    book_id bigint not null references public.books(id) on delete restrict,
    status text not null default 'requested' check (status in ('requested', 'borrowed', 'returned', 'cancelled')),
    requested_at timestamptz not null default now(),
    due_date date not null,
    returned_at timestamptz
);

create table if not exists public.polls (
    id bigint generated by default as identity primary key,
    question text not null,
    active boolean not null default true,
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now()
);

create table if not exists public.poll_options (
    id bigint generated by default as identity primary key,
    poll_id bigint not null references public.polls(id) on delete cascade,
    label text not null check (label in ('A', 'B', 'C', 'D', 'E')),
    option_text text not null,
    unique (poll_id, label)
);

create table if not exists public.poll_votes (
    poll_id bigint not null references public.polls(id) on delete cascade,
    option_id bigint not null references public.poll_options(id) on delete cascade,
    user_id uuid not null references public.profiles(id) on delete cascade,
    voted_at timestamptz not null default now(),
    primary key (poll_id, user_id)
);

create table if not exists public.help_questions (
    id bigint generated by default as identity primary key,
    user_id uuid references public.profiles(id) on delete set null,
    name text not null,
    email text not null,
    message text not null,
    status text not null default 'open' check (status in ('open', 'resolved')),
    created_at timestamptz not null default now()
);

create index if not exists idx_articles_status_created on public.articles(status, created_at desc);
create index if not exists idx_books_active_title on public.books(active, title);
create index if not exists idx_loans_user on public.loans(user_id, requested_at desc);
create index if not exists idx_loans_status on public.loans(status);
create index if not exists idx_poll_options_poll on public.poll_options(poll_id);
create index if not exists idx_poll_votes_option on public.poll_votes(option_id);
create index if not exists idx_help_status_created on public.help_questions(status, created_at desc);

-- ============================================================
-- 2. TRIGGERS E FUNÇÕES DE PERFIL
-- ============================================================

create or replace function public.role_from_email(p_email text)
returns text
language sql
immutable
set search_path = ''
as $$
    select case
        when lower(split_part(coalesce(p_email, ''), '@', 2)) = 'prof.educacao.sp.gov.br' then 'admin'
        else 'student'
    end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.profiles (id, full_name, email, role)
    values (
        new.id,
        coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), split_part(coalesce(new.email, 'Aluno'), '@', 1)),
        new.email,
        public.role_from_email(new.email)
    )
    on conflict (id) do update
       set full_name = excluded.full_name,
           email = excluded.email,
           role = excluded.role;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.sync_profile_email()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    update public.profiles
       set email = new.email,
           role = public.role_from_email(new.email)
     where id = new.id;
    return new;
end;
$$;

drop trigger if exists on_auth_user_email_changed on auth.users;
create trigger on_auth_user_email_changed
after update of email on auth.users
for each row execute procedure public.sync_profile_email();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_articles_updated_at on public.articles;
create trigger set_articles_updated_at
before update on public.articles
for each row execute procedure public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
          from public.profiles
         where id = auth.uid()
           and role = 'admin'
    );
$$;

-- ============================================================
-- 3. FUNÇÕES SEGURAS DE NEGÓCIO
-- ============================================================

create or replace function public.request_book_loan(p_book_id bigint)
returns public.loans
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
    v_book public.books%rowtype;
    v_loan public.loans%rowtype;
    v_code text;
begin
    if v_user_id is null then
        raise exception 'Você precisa estar autenticado para solicitar um empréstimo.';
    end if;

    select *
      into v_book
      from public.books
     where id = p_book_id
       and active = true
     for update;

    if not found then
        raise exception 'Livro não encontrado ou inativo.';
    end if;

    if v_book.available_copies <= 0 then
        raise exception 'Não há exemplares disponíveis no momento.';
    end if;

    if exists (
        select 1
          from public.loans
         where user_id = v_user_id
           and book_id = p_book_id
           and status in ('requested', 'borrowed')
    ) then
        raise exception 'Você já possui uma solicitação ou empréstimo ativo deste livro.';
    end if;

    v_code := 'HNW-' || upper(substr(encode(extensions.gen_random_bytes(6), 'hex'), 1, 10));

    update public.books
       set available_copies = available_copies - 1
     where id = p_book_id;

    insert into public.loans (code, user_id, book_id, status, due_date)
    values (v_code, v_user_id, p_book_id, 'requested', current_date + 30)
    returning * into v_loan;

    return v_loan;
end;
$$;

create or replace function public.return_book_loan(p_loan_id bigint)
returns public.loans
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_loan public.loans%rowtype;
begin
    if not public.is_admin() then
        raise exception 'Apenas administradores podem registrar devoluções.';
    end if;

    select *
      into v_loan
      from public.loans
     where id = p_loan_id
     for update;

    if not found then
        raise exception 'Empréstimo não encontrado.';
    end if;

    if v_loan.status in ('returned', 'cancelled') then
        return v_loan;
    end if;

    update public.loans
       set status = 'returned',
           returned_at = now()
     where id = p_loan_id
    returning * into v_loan;

    update public.books
       set available_copies = least(total_copies, available_copies + 1)
     where id = v_loan.book_id;

    return v_loan;
end;
$$;

create or replace function public.vote_poll(p_poll_id bigint, p_option_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user_id uuid := auth.uid();
begin
    if v_user_id is null then
        raise exception 'Você precisa estar autenticado para votar.';
    end if;

    if not exists (
        select 1
          from public.polls p
          join public.poll_options o on o.poll_id = p.id
         where p.id = p_poll_id
           and p.active = true
           and o.id = p_option_id
    ) then
        raise exception 'Enquete ou opção inválida.';
    end if;

    if exists (
        select 1
          from public.poll_votes
         where poll_id = p_poll_id
           and user_id = v_user_id
    ) then
        raise exception 'Você já votou nesta enquete.';
    end if;

    insert into public.poll_votes (poll_id, option_id, user_id)
    values (p_poll_id, p_option_id, v_user_id);
end;
$$;

create or replace function public.get_poll_results()
returns table (
    poll_id bigint,
    option_id bigint,
    votes bigint
)
language sql
stable
security definer
set search_path = ''
as $$
    select
        o.poll_id,
        o.id as option_id,
        count(v.user_id)::bigint as votes
    from public.poll_options o
    join public.polls p on p.id = o.poll_id
    left join public.poll_votes v
      on v.poll_id = o.poll_id
     and v.option_id = o.id
    where p.active = true
    group by o.poll_id, o.id;
$$;

-- ============================================================
-- 4. ROW LEVEL SECURITY (RLS)
-- ============================================================

alter table public.profiles enable row level security;
alter table public.articles enable row level security;
alter table public.article_saves enable row level security;
alter table public.books enable row level security;
alter table public.loans enable row level security;
alter table public.polls enable row level security;
alter table public.poll_options enable row level security;
alter table public.poll_votes enable row level security;
alter table public.help_questions enable row level security;

-- PROFILES
 drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin());

 drop policy if exists "profiles_admin_update" on public.profiles;
create policy "profiles_admin_update"
on public.profiles for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- ARTICLES
 drop policy if exists "articles_public_read" on public.articles;
create policy "articles_public_read"
on public.articles for select
to anon
using (status = 'published');

 drop policy if exists "articles_authenticated_read" on public.articles;
create policy "articles_authenticated_read"
on public.articles for select
to authenticated
using (status = 'published');

 drop policy if exists "articles_admin_read_all" on public.articles;
create policy "articles_admin_read_all"
on public.articles for select
to authenticated
using (public.is_admin());

 drop policy if exists "articles_admin_insert" on public.articles;
create policy "articles_admin_insert"
on public.articles for insert
to authenticated
with check (public.is_admin() and author_id = auth.uid());

 drop policy if exists "articles_admin_update" on public.articles;
create policy "articles_admin_update"
on public.articles for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

 drop policy if exists "articles_admin_delete" on public.articles;
create policy "articles_admin_delete"
on public.articles for delete
to authenticated
using (public.is_admin());

-- ARTICLE SAVES
 drop policy if exists "article_saves_own_select" on public.article_saves;
create policy "article_saves_own_select"
on public.article_saves for select
to authenticated
using (user_id = auth.uid());

 drop policy if exists "article_saves_own_insert" on public.article_saves;
create policy "article_saves_own_insert"
on public.article_saves for insert
to authenticated
with check (user_id = auth.uid());

 drop policy if exists "article_saves_own_delete" on public.article_saves;
create policy "article_saves_own_delete"
on public.article_saves for delete
to authenticated
using (user_id = auth.uid());

-- BOOKS
 drop policy if exists "books_public_read" on public.books;
create policy "books_public_read"
on public.books for select
to anon, authenticated
using (active = true);

 drop policy if exists "books_admin_read_all" on public.books;
create policy "books_admin_read_all"
on public.books for select
to authenticated
using (public.is_admin());

 drop policy if exists "books_admin_insert" on public.books;
create policy "books_admin_insert"
on public.books for insert
to authenticated
with check (public.is_admin());

 drop policy if exists "books_admin_update" on public.books;
create policy "books_admin_update"
on public.books for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

 drop policy if exists "books_admin_delete" on public.books;
create policy "books_admin_delete"
on public.books for delete
to authenticated
using (public.is_admin());

-- LOANS
 drop policy if exists "loans_own_select" on public.loans;
create policy "loans_own_select"
on public.loans for select
to authenticated
using (user_id = auth.uid());

 drop policy if exists "loans_admin_select" on public.loans;
create policy "loans_admin_select"
on public.loans for select
to authenticated
using (public.is_admin());

-- POLLS
 drop policy if exists "polls_public_read" on public.polls;
create policy "polls_public_read"
on public.polls for select
to anon, authenticated
using (active = true);

 drop policy if exists "polls_admin_read_all" on public.polls;
create policy "polls_admin_read_all"
on public.polls for select
to authenticated
using (public.is_admin());

 drop policy if exists "polls_admin_insert" on public.polls;
create policy "polls_admin_insert"
on public.polls for insert
to authenticated
with check (public.is_admin() and created_by = auth.uid());

 drop policy if exists "polls_admin_update" on public.polls;
create policy "polls_admin_update"
on public.polls for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

 drop policy if exists "polls_admin_delete" on public.polls;
create policy "polls_admin_delete"
on public.polls for delete
to authenticated
using (public.is_admin());

-- POLL OPTIONS
 drop policy if exists "poll_options_public_read" on public.poll_options;
create policy "poll_options_public_read"
on public.poll_options for select
to anon, authenticated
using (exists (select 1 from public.polls p where p.id = poll_id and p.active = true));

 drop policy if exists "poll_options_admin_read_all" on public.poll_options;
create policy "poll_options_admin_read_all"
on public.poll_options for select
to authenticated
using (public.is_admin());

 drop policy if exists "poll_options_admin_insert" on public.poll_options;
create policy "poll_options_admin_insert"
on public.poll_options for insert
to authenticated
with check (public.is_admin());

 drop policy if exists "poll_options_admin_update" on public.poll_options;
create policy "poll_options_admin_update"
on public.poll_options for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

 drop policy if exists "poll_options_admin_delete" on public.poll_options;
create policy "poll_options_admin_delete"
on public.poll_options for delete
to authenticated
using (public.is_admin());

-- POLL VOTES: usuário só lê o próprio voto. Inserção ocorre pela função vote_poll().
 drop policy if exists "poll_votes_own_select" on public.poll_votes;
create policy "poll_votes_own_select"
on public.poll_votes for select
to authenticated
using (user_id = auth.uid());

-- HELP QUESTIONS
 drop policy if exists "help_anon_insert" on public.help_questions;
create policy "help_anon_insert"
on public.help_questions for insert
to anon
with check (user_id is null);

 drop policy if exists "help_authenticated_insert" on public.help_questions;
create policy "help_authenticated_insert"
on public.help_questions for insert
to authenticated
with check (user_id = auth.uid());

 drop policy if exists "help_admin_select" on public.help_questions;
create policy "help_admin_select"
on public.help_questions for select
to authenticated
using (public.is_admin());

 drop policy if exists "help_admin_update" on public.help_questions;
create policy "help_admin_update"
on public.help_questions for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

 drop policy if exists "help_admin_delete" on public.help_questions;
create policy "help_admin_delete"
on public.help_questions for delete
to authenticated
using (public.is_admin());

-- ============================================================
-- 5. PERMISSÕES DA DATA API
-- RLS continua sendo a camada que decide quais linhas cada usuário acessa.
-- ============================================================

grant usage on schema public to anon, authenticated;

grant select on public.articles, public.books, public.polls, public.poll_options to anon;
grant insert on public.help_questions to anon;

grant select on public.profiles, public.articles, public.article_saves, public.books,
    public.loans, public.polls, public.poll_options, public.poll_votes, public.help_questions
    to authenticated;

grant insert, update, delete on public.articles, public.books, public.polls, public.poll_options, public.help_questions
    to authenticated;
grant insert, delete on public.article_saves to authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;

grant execute on function public.is_admin() to authenticated;
grant execute on function public.request_book_loan(bigint) to authenticated;
grant execute on function public.return_book_loan(bigint) to authenticated;
grant execute on function public.vote_poll(bigint, bigint) to authenticated;
grant execute on function public.get_poll_results() to anon, authenticated;

-- ============================================================
-- 6. DADOS INICIAIS DO HENRINEWS
-- ============================================================

insert into public.articles (title, content, image_url, status)
select
    'Primeiras Bancas do TCC: 3º A Apresenta Propostas de Projetos Para Professores e Gestão',
    'O 3º ano A deu o pontapé inicial nos trabalhos de conclusão de curso com a realização das primeiras bancas de apresentação. Diante dos professores, do diretor e do coordenador, os estudantes defenderam as propostas e o planejamento do que pretendem desenvolver ao longo dos próximos meses. A banca avaliou a viabilidade de quatro projetos promissores: o planejamento de automação para uma Padaria; uma iniciativa voltada para a área da Saúde; a estrutura inicial do novo Jornal da Escola; e o conceito cultural do Museu da Tecnologia. Agora, com o sinal verde e os conselhos dos avaliadores, os grupos começam oficialmente a fase de execução das ideias.',
    'https://regrasparatcc.com.br/wp-content/uploads/2025/08/image.jpeg',
    'published'
where not exists (
    select 1 from public.articles where title = 'Primeiras Bancas do TCC: 3º A Apresenta Propostas de Projetos Para Professores e Gestão'
);

insert into public.articles (title, content, image_url, status)
select
    'Novo acervo de Literatura Clássica chega à biblioteca',
    'Graças às sugestões do Grêmio Estudantil, recebemos mais de 40 novos títulos de literatura brasileira e internacional para compor as leituras obrigatórias dos principais vestibulares nacionais. Venha conferir os novos exemplares já cadastrados no nosso sistema digital de reservas.',
    'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&q=80',
    'published'
where not exists (
    select 1 from public.articles where title = 'Novo acervo de Literatura Clássica chega à biblioteca'
);

insert into public.books (title, author, description, total_copies, available_copies)
select 'Dom Casmurro', 'Machado de Assis', 'Clássico do realismo brasileiro focado no mistério de Capitu.', 1, 1
where not exists (select 1 from public.books where title = 'Dom Casmurro' and author = 'Machado de Assis');

insert into public.books (title, author, description, total_copies, available_copies)
select 'O Cortiço', 'Aluísio Azevedo', 'Obra do naturalismo que analisa o comportamento coletivo urbano.', 1, 1
where not exists (select 1 from public.books where title = 'O Cortiço' and author = 'Aluísio Azevedo');

insert into public.books (title, author, description, total_copies, available_copies)
select 'Quincas Borba', 'Machado de Assis', 'Crítica social marcada pela filosofia do Humanitismo.', 1, 1
where not exists (select 1 from public.books where title = 'Quincas Borba' and author = 'Machado de Assis');

insert into public.books (title, author, description, total_copies, available_copies)
select 'Antologia Poética', 'Carlos Drummond de Andrade', 'Seleção de poemas e reflexões sobre a vida e o cotidiano.', 1, 1
where not exists (select 1 from public.books where title = 'Antologia Poética' and author = 'Carlos Drummond de Andrade');

do $$
declare
    v_poll_id bigint;
begin
    if not exists (select 1 from public.polls where question = 'Qual deve ser o tema do próximo evento cultural da escola?') then
        insert into public.polls (question, active)
        values ('Qual deve ser o tema do próximo evento cultural da escola?', true)
        returning id into v_poll_id;

        insert into public.poll_options (poll_id, label, option_text) values
            (v_poll_id, 'A', 'Cultura Geek e Tecnologia'),
            (v_poll_id, 'B', 'Arte Moderna e Grafite'),
            (v_poll_id, 'C', 'Música Regional Brasileira');
    end if;
end $$;

commit;

-- ============================================================
-- 7. PRIMEIRO ADMINISTRADOR
-- ============================================================
-- 1) Abra o HenriNews e crie normalmente a sua conta.
-- 2) Confirme o e-mail, se essa opção estiver habilitada no Supabase Auth.
-- 3) Depois execute SOMENTE a linha abaixo, trocando pelo e-mail do gestor:
--
-- update public.profiles set role = 'admin' where email = 'gestor@escola.com';
--
-- Nunca coloque a service_role key no script.js ou no navegador.
